version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Australia/Brisbane"
    allow:
      - dependency-type: direct
    labels:
      - "automerge"
      - "dependencies"
    ignore:
      # Ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 3
