# .kodiak.toml
# Minimal config. version is the only required field.

# This is for automerging dependabot PRs

version = 1

# https://kodiakhq.com/docs/config-reference#mergeautomerge_dependenciesversions
merge.automerge_dependencies.versions = ["minor", "patch"]

# https://kodiakhq.com/docs/config-reference#mergemethod
merge.method = "rebase"

# https://kodiakhq.com/docs/config-reference#mergeoptimistic_updates
merge.optimistic_updates = false

https://kodiakhq.com/docs/config-reference#mergenotify_on_conflict
merge.notify_on_conflict = false

https://kodiakhq.com/docs/config-reference#mergeprioritize_ready_to_merge
merge.prioritize_ready_to_merge = true