name: Build Size Diff

on: [pull_request]

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      # https://github.com/preactjs/compressed-size-action
      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: "build"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          strip-hash: "\\.(\\w*?)\\."
          pattern: "dist/**/*.{css,js,json,html}"
